//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace DiagCore.App.Resources;

using System;
using System.Globalization;
using System.Resources;

[System.CodeDom.Compiler.GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
[System.Diagnostics.DebuggerNonUserCode]
[System.Runtime.CompilerServices.CompilerGenerated]
public class Strings
{
    private static ResourceManager? resourceMan;
    private static CultureInfo? resourceCulture;

    internal Strings()
    {
    }

    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]
    public static ResourceManager ResourceManager
    {
        get
        {
            if (resourceMan is null)
            {
                resourceMan = new ResourceManager("DiagCore.App.Resources.Strings", typeof(Strings).Assembly);
            }
            return resourceMan;
        }
    }

    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]
    public static CultureInfo? Culture
    {
        get => resourceCulture;
        set => resourceCulture = value;
    }

    public static string AppTitle => ResourceManager.GetString(nameof(AppTitle), resourceCulture) ?? string.Empty;

    public static string StatusBarFooter => ResourceManager.GetString(nameof(StatusBarFooter), resourceCulture) ?? string.Empty;

    public static string PlaceholderSubtitle => ResourceManager.GetString(nameof(PlaceholderSubtitle), resourceCulture) ?? string.Empty;

    public static string Nav_Home => ResourceManager.GetString("Nav.Home", resourceCulture) ?? string.Empty;

    public static string Nav_Hardware => ResourceManager.GetString("Nav.Hardware", resourceCulture) ?? string.Empty;

    public static string Nav_Storage => ResourceManager.GetString("Nav.Storage", resourceCulture) ?? string.Empty;

    public static string Nav_Network => ResourceManager.GetString("Nav.Network", resourceCulture) ?? string.Empty;

    public static string Nav_Security => ResourceManager.GetString("Nav.Security", resourceCulture) ?? string.Empty;

    public static string Nav_Reports => ResourceManager.GetString("Nav.Reports", resourceCulture) ?? string.Empty;

    public static string Nav_Settings => ResourceManager.GetString("Nav.Settings", resourceCulture) ?? string.Empty;
}
